maximum_email: 255
maximum_name: 50
minimum_password: 6
avatar_size: 80
remember_active: "1"
user_avatar: 50
number_of_page: 20
expired_time: 2
maximum_length_content: 140
size_picture: 5
resize_picture: 400
number_of_post: 20
